# Generated by Django 5.0.11 on 2025-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_contactinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="about_images/"),
                ),
            ],
        ),
    ]
