# Generated by Django 5.0.11 on 2025-02-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_aboutus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutus",
            name="image",
        ),
        migrations.AddField(
            model_name="aboutus",
            name="logo",
            field=models.ImageField(
                default="logos/default_logo.png", upload_to="logos/"
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
