# Generated by Django 5.0.11 on 2025-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_remove_aboutus_image_aboutus_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="about_images/"),
        ),
    ]
