# Generated by Django 5.0.11 on 2025-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_aboutus_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
