# Generated by Django 5.0.11 on 2025-02-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_legalpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegalPage",
        ),
    ]
