# Generated by Django 5.0.11 on 2025-02-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_delete_legalpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Privacy Policy", max_length=255)),
                ("content", models.TextField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Terms & Conditions", max_length=255),
                ),
                ("content", models.TextField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
