# Generated by Django 5.0.11 on 2025-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_privacypolicy_termsandconditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelcomeText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="termsandconditions",
            name="logo",
        ),
    ]
