# Generated by Django 5.0.11 on 2025-02-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_welcometext_remove_aboutus_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="welcometext",
            name="title",
            field=models.CharField(
                default="Welcome to Nagarik Badapatra Nepal", max_length=255
            ),
        ),
    ]
