# Generated by Django 5.0.11 on 2025-02-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_welcometext_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinfo",
            old_name="name",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="whatsapp",
        ),
    ]
