# Generated by Django 5.0.11 on 2025-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_rename_name_contactinfo_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinfo",
            old_name="address",
            new_name="name",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="whatsapp",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
