# Generated by Django 5.0.11 on 2025-02-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_rename_address_contactinfo_name_contactinfo_logo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinfo",
            old_name="name",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="whatsapp",
        ),
    ]
