# Generated by Django 5.0.11 on 2025-02-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_rename_name_contactinfo_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinfo",
            old_name="address",
            new_name="name",
        ),
    ]
