# Generated by Django 5.0.11 on 2025-02-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_rename_address_contactinfo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
